In [1]:
# NUMPY
import pandas as pd
import numpy as np

In [52]:
# Creación e indexación
# 1.1 Crea un array 1D con 50 valores aleatorio del 10 al 99. 
array1d = np.random.randint(10,100,(50))
print (array1d)
# 1.2 Accede a los elementos en las posiciones múltiplos de 5.
array1d[4::5]

[67 72 87 78 64 18 48 42 90 73 49 14 57 83 82 18 98 89 63 84 92 92 56 16
 91 74 76 93 71 93 97 34 52 21 61 73 99 40 49 60 42 65 26 19 12 18 91 87
 86 83]


array([64, 73, 82, 84, 91, 93, 61, 60, 12, 83])

In [53]:
# 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). 
# Utiliza indexación para obtener los elementos en las posiciones impares.
array1d =np.random.randint(1,21, (30))
print (array1d)
array1d[::2]

[13  1 10  8  8  3  7 15 18 16  7 20 13 16 16  4 12 11  2 11  7 13  3 18
 14 20 16  9  8  9]


array([13, 10,  8,  7, 18,  7, 13, 16, 12,  2,  7,  3, 14, 16,  8])

In [108]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
array2d = np.random.rand(4,6)
print (array2d)
print ("Esta es la ultima fila de la matriz:", array2d[-1::])
array2d_round = np.round(array2d, 2)
print ( "Matriz redondeada:" , array2d_round)
print ( "Ultima fila matriz redondeada:", array2d_round[-1::])


[[0.8066744  0.72840208 0.66050432 0.09198185 0.66400451 0.84960971]
 [0.07084945 0.30022351 0.99522646 0.12778371 0.23155302 0.98100081]
 [0.08397163 0.06626379 0.47692543 0.29248907 0.25822045 0.98903289]
 [0.19581925 0.5469863  0.6102526  0.22981013 0.42230193 0.32007913]]
Esta es la ultima fila de la matriz: [[0.19581925 0.5469863  0.6102526  0.22981013 0.42230193 0.32007913]]
Matriz redondeada: [[0.81 0.73 0.66 0.09 0.66 0.85]
 [0.07 0.3  1.   0.13 0.23 0.98]
 [0.08 0.07 0.48 0.29 0.26 0.99]
 [0.2  0.55 0.61 0.23 0.42 0.32]]
Ultima fila matriz redondeada: [[0.2  0.55 0.61 0.23 0.42 0.32]]


In [129]:
# 4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). 
array3d = np.random.randint(0,101,(2,3,5))
print ("Array 3d:", array3d)
type(array3d)
# Reemplaza los elementos en posiciones múltiplos de 3 por 0.
# Hay que crear una máscara booleana para identificar los múltiplos de 3 ( = True)
mask_multiplos3 = (array3d % 3 == 0)
print ("máscara multiplos de 3:")
print(mask_multiplos3)
# Reemplazar por 0 - Modificando directamente el array utilizando la máscara booleana
array3d[mask_multiplos3] = 0
print("Array multiplos 3 = 0")
print (array3d)

Array 3d: [[[55 39 11  5 63]
  [57  8 46 88 21]
  [91 93 78 56 23]]

 [[68 46 93 33 50]
  [77 36 10 48  9]
  [25 95 61 41 70]]]
máscara multiplos de 3:
[[[False  True False False  True]
  [ True False False False  True]
  [False  True  True False False]]

 [[False False  True  True False]
  [False  True False  True  True]
  [False False False False False]]]
Array multiplos 3 = 0
[[[55  0 11  5  0]
  [ 0  8 46 88  0]
  [91  0  0 56 23]]

 [[68 46  0  0 50]
  [77  0 10  0  0]
  [25 95 61 41 70]]]


In [83]:
# RESHAPE Y TRANSPOSE
# Ejercicios con reshape:
# 1.1 Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
array3d = np.random.randint (1,101,(2,3,4))
print (array3d)
# 1.2 Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.
# Los datos del array3d en 2d tendrían la forma(6,4) (2*3)+ 4 columnas
array_2d = array3d.reshape(-1, array3d.shape[-1]) # -1 se usa como marcador de posición para el tamaño de la primera dimensión, lo que permite a Numpy calcular automáticamente el tamaño apropiado en función del número total de elementos. array_3d.shape[-1] significa que mantenemos el tamaño de la última dimensión es la misma.
print(array_2d)

[[[10 44 39 75]
  [17 61 29 84]
  [98 90 93 60]]

 [[ 8  7 38 27]
  [49 39  9 19]
  [15 54 85 92]]]
[[10 44 39 75]
 [17 61 29 84]
 [98 90 93 60]
 [ 8  7 38 27]
 [49 39  9 19]
 [15 54 85 92]]


In [88]:
# 2.1 Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). 
array_3d = np.random.randint(2, 60, (3,4,5))
print (array_3d)
# 2.2 Utiliza reshape para convertirlo en un array 2D.
# Para 2D tendrá que tener shape: (12, 5)
array_2d = array_3d.reshape(12,5)
print (array_2d)

[[[26 57 40 37 28]
  [26 12 26  9 54]
  [17 54  5  5 48]
  [17 52 33  7 51]]

 [[ 5 13 32 15  2]
  [18  6 52  3 52]
  [45 43  6 46 57]
  [53 21 21  3 19]]

 [[ 8 42  7  6 36]
  [34 50  2 51 11]
  [ 3  3 22 36 19]
  [46 46 38 26 41]]]
[[26 57 40 37 28]
 [26 12 26  9 54]
 [17 54  5  5 48]
 [17 52 33  7 51]
 [ 5 13 32 15  2]
 [18  6 52  3 52]
 [45 43  6 46 57]
 [53 21 21  3 19]
 [ 8 42  7  6 36]
 [34 50  2 51 11]
 [ 3  3 22 36 19]
 [46 46 38 26 41]]


In [91]:
# Ejercicios con transpose
# 3.1 Utiliza el array 3D del ejercicio 2 de reshape. 
# Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
transpose_array_3d = array_3d.transpose()
print (transpose_array_3d)


[[[26  5  8]
  [26 18 34]
  [17 45  3]
  [17 53 46]]

 [[57 13 42]
  [12  6 50]
  [54 43  3]
  [52 21 46]]

 [[40 32  7]
  [26 52  2]
  [ 5  6 22]
  [33 21 38]]

 [[37 15  6]
  [ 9  3 51]
  [ 5 46 36]
  [ 7  3 26]]

 [[28  2 36]
  [54 52 11]
  [48 57 19]
  [51 19 41]]]


In [102]:
# 4.1  Utiliza el array 3D del ejercicio 2 de reshape. 
# Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).
nuevo_transpose = np.transpose(array_3d, (0,1,2)) # el 3 lo mantego e invierto filas por columnas con 1 y 2.
print (nuevo_transpose)


[[[26 57 40 37 28]
  [26 12 26  9 54]
  [17 54  5  5 48]
  [17 52 33  7 51]]

 [[ 5 13 32 15  2]
  [18  6 52  3 52]
  [45 43  6 46 57]
  [53 21 21  3 19]]

 [[ 8 42  7  6 36]
  [34 50  2 51 11]
  [ 3  3 22 36 19]
  [46 46 38 26 41]]]


In [ ]:
# Preguntas teóricas:
# 1. ¿Qué diferencia existe entre el reshape y el transpose?
# El reshape nos permite alterar las dimensiones de un array (pasarlo por ejemplo de 3 dimensiones a 2 o de 2 a 1), cambia la forma (shape) del array.
# El transpose no cambia la forma del array en sí mismo solo mueve, desplaza, transpone sus valores. Intercambia sus posiciones.

# 2. ¿Y entre el transpose y el swapaxes?
# En el transpose podemos alterar todos los valores especificando la forma exacta. El swapaxes solo intercambia un eje por el otro. Esta es su sintaxis: swapped_arr_3d = np.swapaxes(arr_3d, 0, 2) Solo admite 2 ejes.

In [121]:
# FUNCIONES ARITMÉTICAS Y ESTADÍSTICAS:
# 1 Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.
# array = np.random.random_sample((2,3,5))
# array_dec = np.round(array, 1)
# Se puede hacer todo en una límnea asi: 
array = np.round(np.random.rand(2, 3, 5), 1)
print (array)


[[[0.4 0.3 0.1 0.1 0.1]
  [0.6 1.  0.1 0.9 0.8]
  [0.9 1.  0.3 0.1 0.6]]

 [[0.5 0.5 0.5 0.3 0.8]
  [0.5 0.1 0.5 0.1 0.8]
  [0.8 0.3 0.2 0.7 0.4]]]


In [127]:
# 2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
array_vacio = np.empty (array.shape, dtype = str)
# Calculo: La media de los elementos
media = np.mean(array)
# 2.1 Si el valor del array es igual que la media, se reemplaza por "A".
array_vacio[array_3d == media] = 'A'
# 2.2 Si el valor del array es mayor que la media, se reemplaza por "B".
array_vacio[array > media] = "B"
# 2.3 Si el valor del array es menor que la media, se reemplaza por "C".
array_vacio [array < media] = "C"
# 2.4 Si el valor es igual que el máximo, se reemplaza por "D".
maximo = np.max(array)
array_vacio [array == maximo] = "D"
# 2.5 Si el valor es igual que el mínimo, se reemplaza por "E".
minimo = np.min(array)
array_vacio [array == minimo] = "E"
print("Nuevo array modificado con letras")
print (array_vacio)

Nuevo array modificado con letras
[[['C' 'C' 'E' 'E' 'E']
  ['B' 'D' 'E' 'B' 'B']
  ['B' 'D' 'C' 'E' 'B']]

 [['B' 'B' 'B' 'C' 'B']
  ['B' 'E' 'B' 'E' 'B']
  ['B' 'C' 'C' 'B' 'C']]]
